### PR TITLE
For ZCatalog counter queries, don't do unnecessary sort and brains instanciation

### PR DESCRIPTION
**Pull request by vincentfretin**

### CODE REVIEW

**Comment by vincentfretin** [comment]
On my project, I have 5 faceted_counter queries.
before the change: 39ms, 51ms, 70ms, 154ms, 141ms
after the change: 16ms, 38ms, 32ms, 55ms, 40ms

**Comment by vincentfretin** [comment]
The second commit adds b_start and b_size to the query to allow the zcatalog to sort only the needed number of results. It should allow a perf gain for a large database.

**Comment by vincentfretin** [comment]
I think you can try to cherry-pick the commits to master after merge to plone4 branch. If it don't work, I will do another PR.

**Comment by avoinea** [comment]
@vincentfretin Didn't work with cherry-pick. Can you give it a try, please?

**Comment by vincentfretin** [comment]
I did it with cherrypicking one commit at a time, resolving conflict, git add file_with_conflict, git cherry-pick --continue, removing the comment about conflict.

**Pull request merged**
