### PR TITLE
Bug Fix for FieldIndex: decode utf-8

### PR DESCRIPTION
**Pull request by ksuess**
Faceted navigation fails with no results if option with umlauts is
selected.

### CODE REVIEW

**Comment by avoinea** [comment]
@ksuess Thank you for your contribution. 

Unfortunately the [tests are failing](http://ci.eionet.europa.eu/blue/organizations/jenkins/eea%2Feea.facetednavigation/detail/ksuess/2/pipeline)

**Comment by ksuess** [comment]
@avoinea Yes I see that the Travis CI build failed for my four lines of code. But unfortunatly I'm not familiar with Travis to handle the information of the bug report "Could not find .travis.yml, using standard configuration." Isn't it a add-on thing to configure Travis. I don't see the connection to my pull request.

**Comment by avoinea** [comment]
@ksuess Can you please update your fork in order to run the latest travis check and to fix:
```
This branch has conflicts that must be resolved
```

**Comment by avoinea** [comment]
@ksuess Can you please re-sync your fork?! 

Sorry for the ping-pong, but there were issues within .travis.yml

**Pull request closed without merging**
